# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorkflowSandbox < Formula
  desc "A sandbox for GitHub Actions workflows"
  homepage "https://github.com/merschformann/workflow-sandbox"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merschformann/workflow-sandbox/releases/download/v0.0.2/workflow-sandbox_0.0.2_darwin_amd64.tar.gz"
      sha256 "1ccd15bc7c3660a5a768670910397d48baf09a6a01aa8b34c105a1912a77abfe"

      def install
        bin.install "workflow-sandbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merschformann/workflow-sandbox/releases/download/v0.0.2/workflow-sandbox_0.0.2_darwin_arm64.tar.gz"
      sha256 "96076d9ba3b820c70607f56ef0e1393934ba1dc17157bfa3b82975c533a2c33d"

      def install
        bin.install "workflow-sandbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merschformann/workflow-sandbox/releases/download/v0.0.2/workflow-sandbox_0.0.2_linux_amd64.tar.gz"
        sha256 "b35f3f7102d1a37260d22d8989d1d764c20ab99213d2475a20add6b98017ae3c"

        def install
          bin.install "workflow-sandbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/merschformann/workflow-sandbox/releases/download/v0.0.2/workflow-sandbox_0.0.2_linux_armv6.tar.gz"
        sha256 "1c902f5af9ac795e9ece43b7cf9630a57abe5361b450b7fbf615fbf6c0dfe4ef"

        def install
          bin.install "workflow-sandbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merschformann/workflow-sandbox/releases/download/v0.0.2/workflow-sandbox_0.0.2_linux_arm64.tar.gz"
        sha256 "47a1362bb8890ea414dd6123a7e0e9ddaa1e37f9a3a40bc1da9e73f0b7dbdfcd"

        def install
          bin.install "workflow-sandbox"
        end
      end
    end
  end
end
